### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by AnnamariaTatrai** [AnnamariaTatrai/Balance#1]
The first step is to build the dataset including all waves, but only selected variables.

**Comment by AnnamariaTatrai** [comment]
@anel-li can you please preapare the list of relevant variables ? A vector would be great for that.

**Comment by AnnamariaTatrai** [comment]
Data preparation is finished. We can load Rdata in the next step.

**Comment by anel-li** [comment]
ANAvars <- c("ppltrst", "pplfair", "pplhlp", "trstprl", "trstlgl", "trstplc", "trstplt", "trstprt", "trstep", "trstun",
            "vote", "stflife", "stfeco", "stfgov", "stfdem", "happy", "health", "hhmmb", "gndr", "agea", "yrbrn", "eisced")


Gesendet von Mail für Windows 10

Von: AnnamariaTatrai
Gesendet: Mittwoch, 27. Januar 2021 13:01
An: AnnamariaTatrai/Balance
Cc: el.le; Mention
Betreff: Re: [AnnamariaTatrai/Balance] Data Preparation (#1)

Data preparation is finished. We can load Rdata in the next step.
