### ISSUE TITLE
Data quality check (missing + sraightliners)

### ISSUE THREAD

**Issue by AnnamariaTatrai** [AnnamariaTatrai/Balance#3]
We have to check the quality of data in terms of
- missing cases
- straightlining

**Comment by anel-li** [comment]
I think you solved that, but we should create a table showing, how many cases we dropped due to quality issues

**Comment by anel-li** [comment]
sorry, i didnt wanted to close it, i just wanted to comment

**Comment by anel-li** [comment]
- [ ] this is an item list
- [ ] item 2
- [ ] we can add tasks, that we check later on

**Comment by AnnamariaTatrai** [comment]
done :)
